### ISSUE TITLE
High GPU Memory Usage on RTX 3070 (8GB) with Default Configuration

### ISSUE THREAD

**Issue by arnavk23** [QingyongHu/RandLA-Net#292]
I'm encountering high GPU memory usage similar to [[issue #277](https://github.com/QingyongHu/RandLA-Net/issues/277)](https://github.com/QingyongHu/RandLA-Net/issues/277). Running the same configuration (batch size = 6, N = 4096×11) consumes excessive GPU memory on my system, leading to crashes or OOM issues.

**Environment**:

* **GPU**: NVIDIA RTX 3070 (8GB)
* **Driver Version**: 550.144.03
* **CUDA Host Version**: 12.4
* **CUDA Container Version**: 11.3.1 (via NVIDIA NGC container)
* **TensorFlow**: 2.6
* **Running in Docker?**: Yes, with NVIDIA container runtime
* **OS**: Ubuntu (Docker host)

**Observed Behavior**:

* Running the standard config (`batch_size=6`, `N=4096×11`) quickly exhausts GPU memory (\~8GB)
* Reducing batch size and N does not change memory consumption
* This is surprising since others report it works on a 2080 Ti (12GB)

**Attempts**:

* Ran from inside NVIDIA container (CUDA 11.3.1)
* Tried modifying batch size and point count — no noticeable effect
* Used `tf.config.experimental.set_memory_growth(gpu, True)` but memory usage stayed the same

**Questions**:

1. Is this a known TensorFlow or config-related issue?
2. Are there environment versions (e.g., TF 2.10+) that mitigate this?
3. Any recommended setup or optimization flags to reduce GPU load?

Thanks in advance for your help!

**Comment by joyrksht** [comment]
Hi [arnavk23](https://github.com/arnavk23),
I’m surprised you were able to use TensorFlow 2, since the code is more or less compatible only up to TensorFlow 1.5.

I’ve been working on this repository for a long time and couldn’t find any TensorFlow 2 compatible version. In addition, I encountered this issue after moving my workspace to a newer GPU (A100).

This turned out to be purely a driver-related problem. I resolved it by using a suitable Docker image from the NVIDIA website:
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow/tags?version=25.02-tf2-py3-igpu

It worked for me, and I hope it works for you as well.

Best,
Joy
